### ISSUE TITLE
Render any loaded file

### ISSUE THREAD

**Issue by snowolfe** [asciidoctor/asciidoctor-firefox-addon#18]
Enhancement request

Similar to https://github.com/asciidoctor/asciidoctor-firefox-addon/issues/17

Can we right-click the Add-on icon and offer a menu to change configuration, enable/disable, and render the current page (for non recognised files). Left-click would continue to do as it does now: enable/disable the Add-on.

**Comment by ggrossetie** [comment]
With WebExtension, this means loading the content scripts on all URL which can be bad for performance.
With the new extension you can render `.txt` and there's a proposal to enable the rendering based on the  `Content-Type`:  https://github.com/asciidoctor/asciidoctor-chrome-extension/issues/144

@snowolfe Let me know if this cover your use case. Otherwise could you please open a new issue here: https://github.com/asciidoctor/asciidoctor-chrome-extension thanks
