### ISSUE TITLE
not compatible with iceweasel 38.3

### ISSUE THREAD

**Issue by getreu** [asciidoctor/asciidoctor-firefox-addon#20]
Plugin git version of today  (latest commit bd972ecba5
Guillaume Grossetie Mogztter authored 18 days ago
) does not load into iceweasel 24.8.0: message: not compatible.

**Comment by Mogztter** [comment]
@getreu Is that still the case with the Asciidoctor addon version 0.3.0 ?

**Comment by getreu** [comment]
With debian 8 comes iceweasel 31.7.0.
The lasted update I could install was Asciidoctor.js Live Preview 0.2.3.1-signed.

Iceweasel did not allow me to update to  Asciidoctor 0.3.2. 
The site:
https://addons.mozilla.org/en-US/firefox/addon/asciidoctorjs-live-preview/ said: 
"Not available for Firefox 31.7.0"

**Comment by Mogztter** [comment]
Firefox 31.7 is a bit old (early 2014) and Asciidoctor 0.3.2 is only compatible with Firefox 34+ (release 1st December 2014). Is there a way to update Iceweasel to a more recent release ?

**Comment by getreu** [comment]
In Debian stable (and derived distributions) the most recent version you can get at the moment is 31.8.0esr-1~deb8u1 through Debian backports. The standard version is 31.6.
There was API change since so asciidoctor-firefox-addon should compile fine for all these older versions, doesn't it?

**Comment by getreu** [comment]
Debian backport brings firefox 38.3  (iceweasel). asciidoctor-firefox-addon 0.3.2 installs without error.

Unfortunately the asciidoc text of a local .adoc file is not rendered. It shows only the raw text.

Do I have to use some switch?

**Comment by Mogztter** [comment]
Nothing happens when you enable/disable the extension (right click on the
icon) ?

Is the extension working with remote files ?

**Comment by getreu** [comment]
I do not see the red/grey "A" icon. It is supposed to be in the upper right corner next to other add-on icons. It is also not on the "Additional Tools and features"  customisation page.

**Comment by getreu** [comment]
Remote documents are rendered.

**Comment by Mogztter** [comment]
Ok thanks, I will try to setup a Docker image with Debian and iceweasel.

**Comment by Mogztter** [comment]
I was able to reproduce this issue.
The problem is that the `system.name` is `"Iceweasel"` and not `"Firefox"`: https://github.com/asciidoctor/asciidoctor-firefox-addon/blob/master/lib/main.js#L8

I'm using this hack to handle both mobile (Fennec) and Desktop (Firefox/Iceweasel) version. The mobile version doesn't have the same SDK and this is the only I found to determine what SDK is available.

Now this should be OK because we are using the same code for `Firefox` and `Fennec`.

![iceweasel](https://cloud.githubusercontent.com/assets/333276/10120182/d8e9ec46-64af-11e5-90b0-981171f25bf5.png)

I will publish the xpi file on GitHub because AMO is taking soooo long to accept new version. That way you will be able to use the latest version on Iceweasel !

**Comment by mojavelinux** [comment]
Nice work!

It amazes me that browsers can't agree to use the navigator element in a sensible way. Every browser wants to be Mozilla, Gecko or Chrome, except browsers that are Mozilla, and they want to be something else. Seriously the strangest situation.

**Comment by getreu** [comment]
Thank you!

**Comment by Mogztter** [comment]
Done: https://github.com/asciidoctor/asciidoctor-firefox-addon/releases/tag/v0.4.1

**Comment by getreu** [comment]
It works! :)

**Comment by Mogztter** [comment]
Yeah ! :tada: :+1: :smile:
