### ISSUE TITLE
:toc: in header does not work

### ISSUE THREAD

**Issue by mellery451** [asciidoctor/asciidoctor-firefox-addon#37]
I have a :toc: declaration in my header. The addon simply won't render the TOC. I've tried the macro version, auto, and nothing. None of them seem to work. The JS impl claims to support :toc:

https://github.com/asciidoctor/asciidoctor.js/issues/113

so I'm confused as to why this doesn't work here.

**Comment by mellery451** [comment]
I'm closing this issue...I managed to get it working after some tweaking of my document, although unfortunately I don't know exactly what I changed. Sorry for the noise.

**Comment by Mogztter** [comment]
The TOC is a bit tricky because the Firefox Add-on converts the document to
embeddable HTML (header and footer disabled).

You can read more about that here:
https://github.com/asciidoctor/asciidoctor-chrome-extension/blob/master/README.adoc#toc
Le 24 sept. 2015 11:44 PM, "Michael Ellery" <notifications@github.com> a
écrit :
