### ISSUE TITLE
Q: stylesheet attribute?

### ISSUE THREAD

**Issue by DaLynxx** [asciidoctor/asciidoctor-firefox-addon#53]
Does the addon handle the asciidoctor attributes "stylesheet" and "stylesdir" (via the options field)?

I.e. can I use another css for the rendering?

I can set the attributes and also get the addon to output them via {stylesheet} and {stylesdir} but it always seems to use the same css.

**Comment by Mogztter** [comment]
Hello @DaLynxx 

Loading files is restricted in a browser environment (for security reasons). So you won't be able to load stylesheet with `stylesheet` and `styledir` attributes.

In the Chrome Extension I've added an option page where you can load custom stylesheet: https://github.com/asciidoctor/asciidoctor-chrome-extension but this feature is not yet available in Firefox because I need to figure out how to implement it.

**Comment by DaLynxx** [comment]
Ah, ok. Thnx!

**Comment by DaLynxx** [comment]
Hm... could I maybe replace some .css file in the xpi file to get the same effect?

**Comment by Mogztter** [comment]
Yes, you can append your styles in https://github.com/asciidoctor/asciidoctor-firefox-addon/blob/master/data/css/asciidoctor.css and create a new xpi files. 
But you might need to sign the xpi file: https://developer.mozilla.org/en-US/Add-ons/Distribution

**Comment by Mogztter** [comment]
@DaLynxx You should be able to load a custom stylesheet in the "Firefox" extension since the Chrome and the Firefox extension had merged. Please install the latest version: https://addons.mozilla.org/en-us/firefox/addon/asciidoctorjs-live-preview
