### ISSUE TITLE
Support :docinfo1:

### ISSUE THREAD

**Issue by msc-** [asciidoctor/asciidoctor-firefox-addon#60]
I use a docinfo.html file to make some small changes to the CSS. ALP ignores the :docinfo1: directive in my file header. Please support this feature.

Although this seems to have no security implication, as docinfo.html is in the same directory as the document, I tried "unsafe" mode. However when set to either "unsafe" or "safe" ALP does not perform live preview. It only does it for "server" or "secure".

**Comment by mojavelinux** [comment]
The browser extension convert to embeddable HTML. The docinfo feature wasn't really designed/intended for that mode. It's intended for publishing and may include content that doesn't work with the embeddable HTML. For small changes to the CSS, the Chrome extension provides the ability to either change the stylesheet or provide a custom CSS file. I think that will lead to a less surprising outcome.

**Comment by msc-** [comment]
I do not use Chrome. I use Firefox. The setting for providing alternative CSS in the Firefox extension applies to all documents being previewed which is a problem. It is also a problem if one wants one's document viewable and looking the same on GitHub as it provides no such setting, as far as I am aware.

The other ways that Asciidoctor provides for providing a custom CSS require provision of the entire style sheet which is a huge problem. I don't know if the preview extensions suffer this. docinfo.html is the only way I know to cascade a few minor changes onto the base style sheet.

I do not know what you mean by "embeddable" HTML or what you can do with docinfo.html that is incompatible with it. I do know that if you do weird stuff with docinfo.html your document will fail HTML5 validation and will not be indexed by search engines. So I think that any competent web developer will avoid that weird stuff. Your response brings to mind metaphors about sharp tools.

I typically use docinfo.html just to add a background to the document and to modify the margins to center the text in the browser window.

**Comment by Mogztter** [comment]
It's a bit of a hack but you could use a Passthrough:

```adoc
++++
<style>
  body {
    background-color: #7FDBFF;
  }
</style>
++++
```

> It is also a problem if one wants one's document viewable and looking the same on GitHub as it provides no such setting, as far as I am aware.

As far as I know, GitHub doesn't support docinfo ? do they ?

**Comment by mojavelinux** [comment]
@msc- I understand you're using Firefox. I had mentioned Chrome because the code is nearly the same (and converging). What I left out was that because we have those features in the Chrome extension, it's reasonable to assume we can have the same functionality in the Firefox add-on. That would include a custom CSS file and/or a custom theme.

> The other ways that Asciidoctor provides for providing a custom CSS require provision of the entire style sheet which is a huge problem. I don't know if the preview extensions suffer this. 

The Chrome extension allows for an add-on CSS file (and an add-on JavaScript file). That's very similar to docinfo. It does apply to all documents, though.

> I do not know what you mean by "embeddable" HTML

The browser extensions only generate the contents of the `<body>` element. That content is then inserted into the template that the extension provides (which loads resources such as highlight.js and Font Awesome). So what they're generating is not exactly the same as when generating a standalone HTML document (typically from the commandline).

>  I do know that if you do weird stuff with docinfo.html your document will fail HTML5 validation and will not be indexed by search engines.

It's not the weird stuff that I'm concerned about. It's that docinfo.html is assumed to be for standalone HTML (aka a full document). So we really need to be looking for a different file that is suitable for the preview context. In other words, we have to think about how to play nicely with how docinfo is used in other contexts.

One possible proposal is to look for a docinfo-html5-preview.html and docinfo-footer-html5-preview.html (or something similar).

> I typically use docinfo.html just to add a background to the document and to modify the margins to center the text in the browser window.

It really sounds to me like what you want is a custom preview theme or the ability to tweak the existing theme. If you had the feature that is available in the Chrome extension to add custom CSS, it seems like you'd be able to accomplish what you want. If not, we can continue thinking about which docinfo file should be picked up.

**Comment by mojavelinux** [comment]
Btw, `:docinfo1:` is now deprecated. We now using `:docinfo: shared` or `:docinfo: private`. We made that change because even I couldn't remember the difference between docinfo, docinfo1 and docinfo2 ;)

**Comment by msc-** [comment]
Thanks for the information. I agree with the change to :docinfo: with values. I could never remember the difference either.

The issue with the add-on CSS in the browser extension is that it applies to all documents previewed. My docinfo additions tend to be document specific. So"docinfo-html5-preview.html and docinfo-footer-html5-preview.html (or something similar)" will be a better solution for me.

Thanks for explaining "embeddable HTML".  Can you include <style> tags within the <body> element?

@Mogztter I believe GitHub uses a modified version of Asciidoctor for preview. I know they have disabled file include. I don't know what else they may have disabled but indeed docinfo does not seem to work. The backgrounds I set via docinfo do not appear.

**Comment by Mogztter** [comment]
> I believe GitHub uses a modified version of Asciidoctor for preview. I know they have disabled file include. 

@msc- Indeed they don't provide an implementation to resolve include directive.

> I don't know what else they may have disabled but indeed docinfo does not seem to work. The backgrounds I set via docinfo do not appear.

@msc- I think it's understandable because they want to keep a visual consistency between repositories and therefore they control how the page is rendered and styled.

> Thanks for explaining "embeddable HTML". Can you include <style> tags within the element?

@msc- Sure, here is an example:

```adoc
= Style!

++++
<style>
  #content>h1:first-child:not([class]) {
    color: white;
  }
  html, body {
    background-color: #333;
  }
</style>
++++

== Section 1
```

And the result!

![style](https://cloud.githubusercontent.com/assets/333276/20486444/087ebe18-b000-11e6-9829-45d144a59330.png)

**Comment by mojavelinux** [comment]
> > I believe GitHub uses a modified version of Asciidoctor for preview. I know they have disabled file include.
>
> @msc- Indeed they don't provide an implementation to resolve include directive.

The correct way to explain it is that they run Asciidoctor in secure mode with the header_footer disabled (so embeddable HTML). Here's the actual invocation: https://github.com/asciidoctor/html-pipeline-asciidoc_filter/blob/master/lib/html/pipeline/asciidoc_filter.rb

**Comment by mojavelinux** [comment]
GitHub also uses is own stylesheet and they strip away all CSS classes. So any feature that relies on CSS does not work. We've found a bunch of workarounds and hacks to get it looking pretty nice, but there are limitations.

**Comment by mojavelinux** [comment]
It's important to understand that the preview on GitHub is always going to be very rough and approximate. It's not meant to be a stylized page. Instead, it's meant to give you a view of the content.

If you want the styled version of the page, that's why we created the gist.asciidoctor.org viewer.

**Comment by mojavelinux** [comment]
I realized what might be the correct solution here that would actually make this work across all the preview tools, including Atom, Chrome, Firefox, etc. We could introduce a shared directory that contains auxiliary assets for preview. We'd search upwards from the current directory to the user's home directory. If we find additional HTML, CSS and/or JavaScript files that follow a certain pattern, then they will be included. In other words, I'm proposing an preview-specific, shared theming system. I think these files are fundamentally different than those that are used for a production site (since the focus is on preview) and therefore should be something core is even worried about.

Now to design how it all works.

**Comment by mojavelinux** [comment]
I agree that global configuration isn't really useful because different projects may have docs that need to be themed in different ways.

**Comment by msc-** [comment]
Thanks for all the helpful comments. I tried a Passthrough; it works with Asciidoctor.js but not with GitHub. I don't like it, partly because it feels wrong to have the HTML/CSS in the main document and partly because the long data URL I am using to add a logo to the page background is a disturbance when editing the file. So I think the auxiliary assets directory idea is worth exploring further.

Sadly I don't think gist.asciidoctor.org helps: it requires action from the viewer of the repo and similar could be accomplished by building the document and putting it in the project's GitHub Pages. A service similar to Doxygen's [CodeDocs](https://codedocs.xyz/) would be helpful in this regard.

Another issue with gist.asciidoctor.org for some projects is that it requires the URL of the document be public.

**Comment by ggrossetie** [comment]
> I do not use Chrome. I use Firefox. 

The Firefox and the Chrome extension had merged. Now you should be able to use a custom stylesheet in Firefox 57 with the latest version of the extension.

The new repository is: https://github.com/asciidoctor/asciidoctor-chrome-extension
