### ISSUE TITLE
Includes with relative paths not working

### ISSUE THREAD

**Issue by sverremb** [asciidoctor/asciidoctor-firefox-addon#63]
See https://github.com/asciidoctor/asciidoctor.js/issues/273

This was reported as an error in the asciidoc extension to Brackets, but is also present in the firefox addon.

**Comment by Mogztter** [comment]
Hellow @sverremb, are you using a Windows path ?

**Comment by sverremb** [comment]
Well, it is a network path, like \\share\folder\file.css.

**Comment by mojavelinux** [comment]
Asciidoctor does support UNC (network) paths, so this is probably part of the recent path fixes in Asciidoctor.js to allow full support for paths.

**Comment by mojavelinux** [comment]
...except I'm still not sure it would work given this is a browser environment. It really depends whether xmlhttprequest can read a file from a UNC. We may be short-circuiting because it cannot. I really can't remember.

> We have a css-file for the asciidoc document on a network share.

That's actually a different case. The Asciidoctor processor doesn't read the CSS when creating an embeddable document, as it does in the browser plugin. The plugin itself may offer a custom stylesheet setting, but that's separate from the processor.

**Comment by ggrossetie** [comment]
We've made a lot of changes in Asciidoctor.js, so this issue may be resolved.

Plus you can now configure a custom stylesheet from the options page with the new browser extension: https://github.com/asciidoctor/asciidoctor-chrome-extension

@sverremb
If it still does not work, please open a new issue here: https://github.com/asciidoctor/asciidoctor-chrome-extension/issues
