### ISSUE TITLE
Disable Firefox multiprocess windows

### ISSUE THREAD

**Issue by bodtx** [asciidoctor/asciidoctor-firefox-addon#65]
With this plugin firefox cannot enable multiprocess tabs
![disabled](http://www.omgubuntu.co.uk/wp-content/uploads/2017/04/firefox-about-support.png)

**Comment by Mogztter** [comment]
Hi @bodtx, thanks for your report.

>  To this end, we have an urgent request for developers of add-ons who have not tested their add-ons for e10s compatibility or switched to WebExtensions already

https://blog.mozilla.org/addons/2016/08/02/multi-process-firefox-and-add-ons-a-call-to-action/

As far as I understand, I need to test my add-on with e10s enabled.
Since Firefox 53+ supports WebExtensions API, I may support e10s only in https://github.com/Mogztter/asciidoctor-webextensions (still a work in progress).

**Comment by Mogztter** [comment]
@bodtx  Could you try to install the latest version: https://addons.mozilla.org/en-us/firefox/addon/asciidoctorjs-live-preview ?

**Comment by bodtx** [comment]
Tested today and it's working on linux FF 56 with V 1.5.5.110


thx


Le 29/10/2017 à 10:43, Guillaume Grossetie a écrit :

**Comment by bodtx** [comment]
To me yes, thx
